services:
  hosta:
    image: lab1:0.2
    container_name: hostA
    networks:
      networka:
        ipv4_address: 10.0.11.2
    privileged: true
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
  hostb:
    image: lab1:0.2
    container_name: hostB
    networks:
      networkb:
        ipv4_address: 10.0.13.2
    privileged: true
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
  router1:
    image: lab1:0.2
    container_name: router1
    networks:
      networka:
        ipv4_address: 10.0.11.1
      network1_2:
        ipv4_address: 10.0.12.3
      network1_4:
        ipv4_address: 10.0.12.195
    privileged: true
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
  router2:
    image: lab1:0.2
    container_name: router2
    networks:
      network1_2:
        ipv4_address: 10.0.12.2
      network2_3:
        ipv4_address: 10.0.12.66
    privileged: true
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
  router3:
    image: lab1:0.2
    container_name: router3
    networks:
      network2_3:
        ipv4_address: 10.0.12.67
      network3_4:
        ipv4_address: 10.0.12.131
      networkb:
        ipv4_address: 10.0.13.1
    privileged: true
    tty: true
    stdin_open: true
    entrypoint: /bin/bash
  router4:
    image: lab1:0.2
    container_name: router4
    networks:
      network1_4:
        ipv4_address: 10.0.12.194
      network3_4:
        ipv4_address: 10.0.12.130
    privileged: true
    tty: true
    stdin_open: true
    entrypoint: /bin/bash

networks:
  networka:
    driver: bridge
    name: networkA
    attachable: true
    ipam:
      config:
        - subnet: 10.0.11.0/24
  network1_2:
    driver: bridge
    name: network1_2
    attachable: true
    ipam:
      config:
        - subnet: 10.0.12.0/26
  network2_3:
    driver: bridge
    name: network2_3
    attachable: true
    ipam:
      config:
        - subnet: 10.0.12.64/26
  network3_4:
    driver: bridge
    name: network3_4
    attachable: true
    ipam:
      config:
        - subnet: 10.0.12.128/26
  network1_4:
    driver: bridge
    name: network1_4
    attachable: true
    ipam:
      config:
        - subnet: 10.0.12.192/26
  networkb:
    driver: bridge
    name: networkB
    attachable: true
    ipam:
      config:
        - subnet: 10.0.13.0/24
