#dockerfile - Haehyun Jung
FROM ubuntu
MAINTAINER u0878794@utah.edu

RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y iputils-ping
RUN apt-get install -y net-tools
RUN apt-get install -y quagga
RUN net.ipv4.ip_forward=1
