#dockerfile - Haehyun Jung
FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y iputils-ping
RUN apt-get install -y net-tools
RUN apt-get install -y quagga
RUN apt-get install -y quagga-doc
RUN apt-get install -y vim
RUN apt-get install -y systemctl
RUN apt-get install -y traceroute
